//! The app command list, read from the `tauri::generate_handler![...]` call in
//! `commands/mod.rs`, so the ACL can't drift from what is actually registered.
//!
//! Shared by `build.rs` (which feeds it to `tauri_build::AppManifest::commands` and writes the
//! `app-commands` permission set) and the tests in `commands/mod.rs`. Std only: `build.rs`
//! includes this file with `#[path]`.

/// The command names registered by the first `generate_handler![...]` in `source`, in order.
///
/// Items are `module::command` paths separated by commas; `//` comments are ignored. Errors on
/// a missing list, an empty list, a malformed item or a duplicate.
pub fn handler_commands(source: &str) -> Result<Vec<String>, String> {
    const OPEN: &str = "generate_handler![";
    let start = source.find(OPEN).ok_or("no generate_handler![...] found")? + OPEN.len();
    let code: String = source[start..]
        .lines()
        .map(|line| line.split("//").next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n");
    let body = &code[..code
        .find(']')
        .ok_or("unterminated generate_handler![...]")?];

    let mut commands: Vec<String> = Vec::new();
    for item in body.split(',').map(str::trim).filter(|s| !s.is_empty()) {
        let name = item.rsplit("::").next().unwrap_or(item).trim();
        let valid = !name.is_empty()
            && !name.starts_with(|c: char| c.is_ascii_digit())
            && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
        if !valid {
            return Err(format!("unexpected generate_handler! item `{item}`"));
        }
        if commands.iter().any(|c| c == name) {
            return Err(format!("command `{name}` registered twice"));
        }
        commands.push(name.to_string());
    }
    if commands.is_empty() {
        return Err("generate_handler![...] is empty".into());
    }
    Ok(commands)
}

/// The ACL permission Tauri generates for allowing `command` (`allow-` + kebab-case).
pub fn allow_permission(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

/// `permissions/app-commands.toml`: one set, `app-commands`, allowing every command.
pub fn all_commands_set(commands: &[String]) -> String {
    let mut out = String::from(
        "# Generated by build.rs from the generate_handler! list in src/commands/mod.rs.\n\
         # Do not edit: add commands to that list instead.\n\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every app command (commands::handler()).\"\n\
         permissions = [\n",
    );
    for command in commands {
        out.push_str(&format!("  \"{}\",\n", allow_permission(command)));
    }
    out.push_str("]\n");
    out
}
