//! Amazon Bedrock integration for the Tauri backend.
//!
//! Port of `src/main/api/bedrock` (client factory, `ConverseService` and the other services behind
//! `BedrockService`), the Bedrock Express routes in `src/main/api/index.ts` and the
//! `bedrock:*` IPC handlers in `src/main/handlers/bedrock-handlers.ts`. The TS code is the source
//! of truth; module docs name the function each piece mirrors.
//!
//! # Modules
//!
//! * [`settings`] — serde mirrors of the store keys the converse path reads (`aws`,
//!   `inferenceParams`, `thinkingMode`, `interleaveThinking`, `guardrailSettings`,
//!   `bedrockSettings`).
//! * [`client`] — `SdkConfig` / runtime client from the `aws` settings (static keys or named
//!   profile, proxy, timeouts).
//! * [`request`] — `prepareCommandParameters` (model quirks, thinking, guardrails) as a pure
//!   JSON function, then conversion to SDK types.
//! * [`convert`] / [`document`] — renderer JSON <-> SDK types, `Document`, and blobs.
//! * [`stream_event`] — SDK stream events -> the exact JSON lines Express wrote.
//! * [`retry`] — throttling retries and region failover.
//! * [`model_info`] — registry facts for the converse path ([`RegistryModelInfo`] is the
//!   default). Prompt-cache placement is the `models` crate's [`PromptCacheManager`].
//! * [`sdk`] — [`SdkConfigSource`] (where service clients come from; tests inject fake HTTP)
//!   and the request/response JSON passthrough used by the services below.
//!
//! Services (each a set of library functions taking settings plus the JSON the renderer / tools
//! send today, returning the JSON they expect):
//!
//! | module | TS | commands / callers |
//! | ------ | -- | ------------------ |
//! | [`image`] | `imageService` | `bedrock:generateImage` (generateImage tool) |
//! | [`image_recognition`] | `imageRecognitionService` | `bedrock:recognizeImage` (recognizeImage tool) |
//! | [`agent`] | `agentService` | `bedrock:invokeAgent`, `bedrock:retrieve`, `retrieve_and_generate` |
//! | [`flow`] | `flowService` | `bedrock:invokeFlow` (invokeFlow tool) |
//! | [`guardrail`] | `guardrailService` | `bedrock_apply_guardrail` |
//! | [`translate`] | `translateService` | `bedrock_translate_*` |
//! | [`inference_profile`] | `inferenceProfileService` | `bedrock_list_application_inference_profiles` |
//! | [`catalog`] | `modelService`, `getModelMaxTokens` | `list_models`, `list_agent_tags`, `bedrock_get_model_max_tokens` |
//! | [`structured_output`] | `structuredOutputService`, `websiteRecommendationFactory` | `get_structured_output`, `get_website_recommendations` |
//! | [`video`] | `movieService` | `bedrock:generateVideo`, `bedrock:startVideoGeneration`, `bedrock:checkVideoStatus`, `bedrock:downloadVideo` (video tools) |
//!
//! `NotificationService` is not ported here: it is Electron UI (OS notifications, window focus)
//! and belongs with the background-agent work in the app crate.
//!
//! # Wiring (app crate)
//!
//! The renderer today does `fetch(`${API_ENDPOINT}/converse/stream`, { body: JSON.stringify(props) })`
//! and parses newline-delimited JSON. The intended Tauri replacement:
//!
//! ```ignore
//! use bedrock::{ConverseRequest, ConverseService, ConverseSettings};
//! use tauri::ipc::Channel;
//! use tokio_util::sync::CancellationToken;
//!
//! struct BedrockState {
//!     service: ConverseService,                                   // ConverseService::default()
//!     streams: std::sync::Mutex<HashMap<String, CancellationToken>>, // request id -> token
//! }
//!
//! #[tauri::command]
//! async fn converse_stream(
//!     state: tauri::State<'_, BedrockState>,
//!     store: tauri::State<'_, StoreState>,
//!     request_id: String,          // generated by the renderer, used by converse_cancel
//!     request: ConverseRequest,    // the same JSON body the renderer POSTs today
//!     on_event: Channel<serde_json::Value>,
//! ) -> Result<(), String> {
//!     let settings: ConverseSettings = /* read aws, inferenceParams, thinkingMode, ... from store */;
//!     let token = CancellationToken::new();
//!     state.streams.lock().unwrap().insert(request_id.clone(), token.clone());
//!     let result = state
//!         .service
//!         .converse_stream(&settings, &request, &token, |event| {
//!             on_event.send(event).map_err(|e| e.to_string())
//!         })
//!         .await;
//!     state.streams.lock().unwrap().remove(&request_id);
//!     // Error bodies: `e.to_json()` is the JSON the Express route sent with a non-200 status,
//!     // so `throw new Error(msg)` in the renderer keeps showing the same text.
//!     result.map_err(|e| e.to_json().to_string())
//! }
//!
//! #[tauri::command]
//! fn converse_cancel(state: tauri::State<'_, BedrockState>, request_id: String) {
//!     if let Some(t) = state.streams.lock().unwrap().remove(&request_id) { t.cancel(); }
//! }
//!
//! #[tauri::command]
//! async fn converse(/* ... */ request: ConverseRequest) -> Result<serde_json::Value, String> {
//!     // Returns the `POST /converse` body (`$metadata`, `output.message`, `stopReason`, `usage`, ...).
//!     state.service.converse(&settings, &request, &CancellationToken::new()).await
//!         .map_err(|e| e.to_json().to_string())
//! }
//! ```
//!
//! Renderer side (`lib/api.ts`): create a `Channel`, `yield` each `onmessage` payload from the
//! async generator exactly as the parsed NDJSON lines were yielded, finish when the `invoke`
//! promise resolves, throw `new Error(message)` when it rejects, and map the `AbortSignal` to
//! `invoke('converse_cancel', { requestId })` (the command then rejects with the `AbortError`
//! JSON from [`Error::to_json`]; surface it as a `DOMException('...', 'AbortError')` so
//! `useAgentChat`'s `error.name === 'AbortError'` check still matches).
//!
//! # Behavior differences from the TS
//!
//! * The Nova system-prompt hint is appended once per request; the TS re-appended it on every
//!   throttling retry because it mutated the request object.
//! * A Nova request without a leading text system block is sent as is instead of crashing.
//! * Errors that happen mid-stream are returned as `Err` after the events already delivered; the
//!   Express route could not report them (headers were already sent).
//! * Error JSON always includes `message` (the JS 500 body dropped it: non-enumerable).
//! * Guardrail trace detail: only `actionReason` / `modelOutput` of `trace.guardrail` are
//!   rendered, not per-policy assessments.
//!
//! * Services build their client from the settings passed to each call; the TS
//!   `TranslateService` / `ImageService` kept a client built from the settings at startup.
//! * `list_agent_tags` returns `[]` (the Express route it fetched never existed).
//!
//! Covered TS tests: the `#[ignore]` integration tests in `tests/` port
//! `agentService`, `flowService`, `guardrailService`, `imageService` and
//! `modelRegionConnectivity` `.integration.test.ts`. `SubAgentRunner.test.ts` depends on
//! delegation policy (`common`) and the background agent service (Task 7/11) and belongs with
//! that port.

pub mod agent;
pub mod catalog;
pub mod client;
pub mod converse;
pub mod convert;
pub mod document;
pub mod error;
pub mod flow;
pub mod guardrail;
pub mod image;
pub mod image_recognition;
pub mod inference_profile;
pub mod model_info;
pub mod request;
pub mod retry;
pub mod sdk;
pub mod settings;
pub mod stream_event;
pub mod structured_output;
pub mod translate;
pub mod video;

pub use client::{load_sdk_config, runtime_client};
pub use converse::{ClientFactory, ConverseService, DefaultClientFactory, EventSource};
pub use error::{Error, Result, ServiceError};
pub use model_info::{
    CacheConfig, CacheableField, ModelInfo, NoModelInfo, RegistryModelInfo, ThinkingType,
};
pub use models::PromptCacheManager;
pub use request::{ConverseRequest, PreparedRequest};
pub use retry::RetryPolicy;
pub use sdk::{DefaultSdkConfig, SdkConfigClients, SdkConfigSource};
pub use settings::{
    AwsSettings, BedrockSettings, ConverseSettings, GuardrailSettings, InferenceConfig,
    ProxyConfiguration, ThinkingMode,
};
pub use tokio_util::sync::CancellationToken;
